# Generated by Django 5.2.7 on 2026-02-28 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "profiles_skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TalentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Senior Software Engineer",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("state_province", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Currently Employed"),
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("freelance", "Freelancer"),
                            ("self_employed", "Self-Employed"),
                        ],
                        default="unemployed",
                        max_length=20,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediately Available"),
                            ("2_weeks", "Available in 2 Weeks"),
                            ("1_month", "Available in 1 Month"),
                            ("3_months", "Available in 3 Months"),
                            ("not_available", "Not Currently Available"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("willing_to_relocate", models.BooleanField(default=False)),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                (
                    "remote_preference",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site Only"),
                            ("remote", "Remote Only"),
                            ("hybrid", "Hybrid"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                (
                    "expected_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "expected_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="ZAR", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("interested_in_jobs", models.BooleanField(default=True)),
                ("interested_in_internships", models.BooleanField(default=False)),
                ("interested_in_volunteer", models.BooleanField(default=False)),
                ("interested_in_skillup", models.BooleanField(default=False)),
                ("completeness_score", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                ("is_searchable", models.BooleanField(default=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Talent Profile",
                "verbose_name_plural": "Talent Profiles",
                "db_table": "profiles_talent",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(blank=True, max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("doctorate", "Doctorate"),
                            ("other", "Other"),
                        ],
                        default="bachelors",
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("activities", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="profiles.talentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "db_table": "profiles_education",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(max_length=255)),
                ("credential_id", models.CharField(blank=True, max_length=255)),
                ("credential_url", models.URLField(blank=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("does_not_expire", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="profiles.talentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "db_table": "profiles_certifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to="profiles.talentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
                "db_table": "profiles_work_experience",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TalentLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("elementary", "Elementary"),
                            ("limited_working", "Limited Working"),
                            ("professional_working", "Professional Working"),
                            ("full_professional", "Full Professional"),
                            ("native", "Native or Bilingual"),
                        ],
                        default="professional_working",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="profiles.talentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "profiles_languages",
                "unique_together": {("profile", "language")},
            },
        ),
        migrations.CreateModel(
            name="TalentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.talentprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talents",
                        to="profiles.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talent Skill",
                "verbose_name_plural": "Talent Skills",
                "db_table": "profiles_talent_skills",
                "ordering": ["-is_primary", "-years_of_experience"],
                "unique_together": {("profile", "skill")},
            },
        ),
    ]
