# Generated by Django 5.2.7 on 2026-03-13 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrphanFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("reviewed", "Reviewed"),
                            ("deleted", "Deleted"),
                            ("restored", "Restored"),
                            ("ignored", "Ignored"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "storage_orphan_files",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("download", "Download"),
                            ("view", "View"),
                            ("delete", "Delete"),
                            ("update", "Update"),
                            ("share", "Share"),
                            ("revoke", "Revoke Access"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_id", models.CharField(db_index=True, max_length=32)),
                ("file_category", models.CharField(blank=True, max_length=50)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("service_name", models.CharField(blank=True, max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "storage_access_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["file_id", "operation"],
                        name="storage_acc_file_id_f92891_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="storage_acc_user_id_fda303_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.CharField(db_index=True, max_length=100)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("user", "User"), ("organization", "Organization")],
                        max_length=20,
                    ),
                ),
                (
                    "total_quota",
                    models.BigIntegerField(
                        default=1073741824, help_text="Total storage quota in bytes"
                    ),
                ),
                ("used_storage", models.BigIntegerField(default=0)),
                ("max_files", models.PositiveIntegerField(default=10000)),
                ("current_files", models.PositiveIntegerField(default=0)),
                ("category_limits", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_quotas",
                "unique_together": {("owner_id", "owner_type")},
            },
        ),
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Sanitized display filename", max_length=255
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original uploaded filename", max_length=255
                    ),
                ),
                ("extension", models.CharField(blank=True, max_length=20)),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profiles/avatars", "Profile Avatar"),
                            ("profiles/cover_images", "Profile Cover Image"),
                            ("applications/resumes", "Resume/CV"),
                            ("applications/cover_letters", "Cover Letter"),
                            ("applications/portfolios", "Portfolio Item"),
                            ("applications/certificates", "Certificate"),
                            ("organizations/logos", "Organization Logo"),
                            ("organizations/banners", "Organization Banner"),
                            ("organizations/documents", "Organization Document"),
                            ("communications/attachments", "Message Attachment"),
                            ("communications/email_attachments", "Email Attachment"),
                            ("website/blog_images", "Blog Image"),
                            ("website/blog_attachments", "Blog Attachment"),
                            ("website/gallery", "Gallery Image"),
                            ("intelligence/cv_uploads", "CV for Processing"),
                            ("intelligence/skill_evidence", "Skill Evidence"),
                            ("media/processed/images", "Processed Image"),
                            ("media/processed/documents", "Processed Document"),
                            ("media/processed/videos", "Processed Video"),
                            ("media/processed/audio", "Processed Audio"),
                            ("temp", "Temporary File"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500, unique=True)),
                (
                    "original_size",
                    models.BigIntegerField(help_text="Original file size in bytes"),
                ),
                (
                    "stored_size",
                    models.BigIntegerField(
                        help_text="Size after processing/encryption"
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        help_text="SHA-256 of original content", max_length=64
                    ),
                ),
                (
                    "checksum_stored",
                    models.CharField(
                        help_text="SHA-256 of stored content", max_length=64
                    ),
                ),
                ("is_encrypted", models.BooleanField(default=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public - Anyone can access"),
                            ("authenticated", "Authenticated - Logged in users only"),
                            ("private", "Private - Owner only"),
                            ("restricted", "Restricted - Specific users/roles"),
                            ("org_members", "Organization Members Only"),
                            ("internal", "Internal - System use only"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "owner_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User"),
                            ("organization", "Organization"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "related_entity_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_info", models.JSONField(blank=True, default=dict)),
                ("threats_detected", models.JSONField(blank=True, default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest_version", models.BooleanField(default=True)),
                ("cdn_url", models.URLField(blank=True, max_length=500, null=True)),
                ("cdn_invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                            ("quarantined", "Quarantined"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="storage.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "storage_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignedURL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("allow_download", models.BooleanField(default=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_by_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_urls",
                        to="storage.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "storage_signed_urls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("process_image", "Process Image"),
                            ("process_document", "Process Document"),
                            ("process_video", "Process Video"),
                            ("process_audio", "Process Audio"),
                            ("generate_thumbnail", "Generate Thumbnail"),
                            ("extract_text", "Extract Text"),
                            ("scan_threats", "Scan for Threats"),
                            ("compress", "Compress"),
                            ("convert_format", "Convert Format"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=255)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=5, help_text="1=highest, 10=lowest"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="storage.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "storage_processing_jobs",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["category", "status"], name="storage_fil_categor_c6408e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["owner_id", "category"], name="storage_fil_owner_i_4cc06c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["related_entity_type", "related_entity_id"],
                name="storage_fil_related_b49bbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["organization_id", "status"],
                name="storage_fil_organiz_746f96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["expires_at", "status"], name="storage_fil_expires_899c56_idx"
            ),
        ),
    ]
