# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("iso2", models.CharField(db_index=True, max_length=2, unique=True)),
                ("iso3", models.CharField(db_index=True, max_length=3, unique=True)),
                ("phone_prefix", models.CharField(blank=True, max_length=10)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("sub_region", models.CharField(blank=True, max_length=50)),
                ("flag_emoji", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "core_countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("native_name", models.CharField(blank=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("flag_emoji", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_rtl", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "core_languages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_industries",
                        to="core.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "db_table": "core_industries",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("email_verified", "Email Verified"),
                            ("profile_created", "Profile Created"),
                            ("photo_uploaded", "Photo Uploaded"),
                            ("cv_uploaded", "CV Uploaded"),
                            ("skills_added", "Skills Added"),
                            ("preferences_set", "Preferences Set"),
                            ("first_match", "First Match Received"),
                            ("complete", "Onboarding Complete"),
                        ],
                        default="registered",
                        max_length=30,
                    ),
                ),
                ("completed_steps", models.JSONField(blank=True, default=list)),
                ("completion_percentage", models.PositiveSmallIntegerField(default=0)),
                ("is_complete", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_onboarding_states",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=150, unique=True)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_platform_settings",
                "ordering": ["key"],
            },
        ),
    ]
