# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVParseResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                ("extracted_skills", models.JSONField(blank=True, default=list)),
                ("extracted_education", models.JSONField(blank=True, default=list)),
                ("extracted_experience", models.JSONField(blank=True, default=list)),
                ("contact_info", models.JSONField(blank=True, default=dict)),
                ("overall_confidence", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_parses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_cv_parse_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("skill_gap", "Skill Gap Analysis"),
                            ("career_path", "Career Path Suggestion"),
                            ("market_demand", "Market Demand Alert"),
                            ("profile_tip", "Profile Improvement Tip"),
                            ("salary", "Salary Benchmark"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_insights",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillTaxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("creative", "Creative"),
                            ("business", "Business"),
                            ("leadership", "Leadership"),
                            ("communication", "Communication"),
                            ("analytical", "Analytical"),
                            ("trades", "Trades & Crafts"),
                            ("agriculture", "Agriculture"),
                            ("health", "Health & Medical"),
                            ("education", "Education & Training"),
                            ("arts", "Arts & Culture"),
                            ("sports", "Sports & Athletics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative names for this skill",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="intelligence.skilltaxonomy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "intelligence_skill_taxonomy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TalentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_completeness", models.FloatField(default=0.0)),
                ("skill_depth", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("education_score", models.FloatField(default=0.0)),
                ("portfolio_score", models.FloatField(default=0.0)),
                ("activity_score", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(db_index=True, default=0.0)),
                ("percentile_rank", models.FloatField(default=0.0)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_talent_scores",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="SkillExtraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_type", models.CharField(default="cv", max_length=50)),
                ("source_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("skill_name", models.CharField(max_length=100)),
                ("confidence", models.FloatField(default=0.0)),
                ("context_snippet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_taxonomy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extractions",
                        to="intelligence.skilltaxonomy",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_skill_extractions",
                "ordering": ["-confidence"],
                "indexes": [
                    models.Index(
                        fields=["user", "skill_name"],
                        name="intelligenc_user_id_a690ad_idx",
                    )
                ],
            },
        ),
    ]
