# Generated by Django 5.2.7 on 2026-02-27 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_read", models.BooleanField(default=False)),
                ("is_replied", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("company_size", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "interest_types",
                    models.JSONField(default=list, help_text="List of interest types"),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_contacted", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Registration",
                "verbose_name_plural": "Partner Registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TalentWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "opportunity_types",
                    models.JSONField(
                        default=list, help_text="List of opportunity types"
                    ),
                ),
                ("skills", models.JSONField(default=list, help_text="List of skills")),
                (
                    "skills_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "preferred_fields",
                    models.JSONField(
                        default=list, help_text="List of preferred fields"
                    ),
                ),
                (
                    "fields_other",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_contacted", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Talent Waitlist",
                "verbose_name_plural": "Talent Waitlist Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
