# Generated by Django 5.2.7 on 2026-03-04 08:07

import django.utils.timezone
import uuid
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blog_id",
                    models.CharField(
                        default=website.models.generate_blog_id,
                        help_text="Short unique ID for sharing (e.g., abc12xyz)",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Brief summary shown in listings", max_length=500
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full blog content (supports Markdown)"),
                ),
                (
                    "featured_image",
                    models.URLField(
                        blank=True, default="", help_text="URL to featured image"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("insights", "Insights"),
                            ("stories", "Success Stories"),
                            ("tips", "Career Tips"),
                            ("news", "Platform News"),
                            ("africa", "Africa Focus"),
                            ("tech", "Technology"),
                            ("skills", "Skills & Learning"),
                        ],
                        default="insights",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(default=list, help_text="List of tags")),
                (
                    "author_name",
                    models.CharField(default="ForgeForth Team", max_length=100),
                ),
                (
                    "author_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "author_bio",
                    models.TextField(blank=True, default="", max_length=300),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
