# Generated by Django 5.2.7 on 2026-03-04 08:41

import django.db.models.deletion
import django.utils.timezone
import uuid
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_add_blogpost_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Path to image in protected storage", max_length=255
                    ),
                ),
                (
                    "thumbnail_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to thumbnail",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alt text for accessibility",
                        max_length=255,
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=500)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(default="image/jpeg", max_length=50)),
                (
                    "upload_token",
                    models.CharField(
                        default=website.models.generate_upload_token,
                        help_text="Token for secure access before blog is published",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Image has been scanned and verified safe",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="featured_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author_avatar_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to image in protected storage (e.g., {blog_id}/featured_xxx.jpg)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image_url",
            field=models.URLField(
                blank=True, default="", help_text="External URL to featured image"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["blog_id"], name="website_blo_blog_id_7b2c8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="website_blo_slug_3a3ea2_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="website_blo_status_3bb34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category"], name="website_blo_categor_e65159_idx"
            ),
        ),
        migrations.AddField(
            model_name="blogimage",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated blog post (optional for temp uploads)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="website.blogpost",
            ),
        ),
    ]
