# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_page_views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("talent_count", models.PositiveIntegerField(default=0)),
                ("employer_count", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("applications_submitted", models.PositiveIntegerField(default=0)),
                ("matches_computed", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("cv_uploads", models.PositiveIntegerField(default=0)),
                ("waitlist_joins", models.PositiveIntegerField(default=0)),
                ("partner_registrations", models.PositiveIntegerField(default=0)),
                ("top_countries", models.JSONField(blank=True, default=list)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_metric_snapshots",
                "ordering": ["-period_start"],
                "unique_together": {("granularity", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("talent_funnel", "Talent Funnel"),
                            ("employer_activity", "Employer Activity"),
                            ("match_quality", "Match Quality"),
                            ("platform_health", "Platform Health"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("file_path", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("profile_view", "Profile Viewed"),
                            ("profile_update", "Profile Updated"),
                            ("cv_upload", "CV Uploaded"),
                            ("search", "Talent/Job Search"),
                            ("opp_view", "Opportunity Viewed"),
                            ("opp_apply", "Application Submitted"),
                            ("message_sent", "Message Sent"),
                            ("match_accepted", "Match Accepted"),
                            ("match_rejected", "Match Rejected"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("signup", "Registration"),
                            ("onboarding", "Onboarding Step Completed"),
                            ("waitlist", "Joined Waitlist"),
                            ("partner_register", "Partner Registration"),
                            ("blog_view", "Blog Article Viewed"),
                            ("notif_read", "Notification Read"),
                            ("custom", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("ref_type", models.CharField(blank=True, max_length=50)),
                ("ref_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_user_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="analytics_u_user_id_859e35_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="analytics_u_event_t_d287a1_idx",
                    ),
                ],
            },
        ),
    ]
