# Generated by Django 5.2.7 on 2026-03-05 08:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentralAdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("actor_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=128)),
                ("target_type", models.CharField(blank=True, max_length=128)),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(db_index=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_admin_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="CentralApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("applicant_id", models.UUIDField(db_index=True)),
                ("opportunity_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("applied_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_applications",
            },
        ),
        migrations.CreateModel(
            name="CentralDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("doc_type", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_documents",
            },
        ),
        migrations.CreateModel(
            name="CentralFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_pct", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_feature_flags",
            },
        ),
        migrations.CreateModel(
            name="CentralMediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_media_files",
            },
        ),
        migrations.CreateModel(
            name="CentralMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("sender_id", models.UUIDField(db_index=True)),
                ("recipient_id", models.UUIDField(db_index=True)),
                ("thread_id", models.UUIDField(db_index=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_messages",
            },
        ),
        migrations.CreateModel(
            name="CentralMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("metric_name", models.CharField(db_index=True, max_length=128)),
                ("metric_value", models.FloatField(default=0.0)),
                ("period", models.CharField(blank=True, max_length=16)),
                ("recorded_at", models.DateTimeField(db_index=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_metric_snapshots",
            },
        ),
        migrations.CreateModel(
            name="CentralNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("recipient_id", models.UUIDField(db_index=True)),
                ("notif_type", models.CharField(blank=True, max_length=64)),
                ("channel", models.CharField(blank=True, max_length=32)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_notifications",
            },
        ),
        migrations.CreateModel(
            name="CentralOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("opp_type", models.CharField(blank=True, max_length=32)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
                ("required_skills", models.JSONField(default=list)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("deadline", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_opportunities",
            },
        ),
        migrations.CreateModel(
            name="CentralOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("org_type", models.CharField(blank=True, max_length=32)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_organizations",
            },
        ),
        migrations.CreateModel(
            name="CentralProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("skills", models.JSONField(default=list)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("availability", models.CharField(blank=True, max_length=32)),
                ("employment_status", models.CharField(blank=True, max_length=32)),
                ("is_public", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_profiles",
            },
        ),
        migrations.CreateModel(
            name="CentralSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_skills",
            },
        ),
        migrations.CreateModel(
            name="CentralSkillExtraction",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("profile_id", models.UUIDField(db_index=True)),
                ("extracted_skills", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.0)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_skill_extractions",
            },
        ),
        migrations.CreateModel(
            name="CentralTalentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("profile_id", models.UUIDField(db_index=True)),
                ("overall_score", models.FloatField(default=0.0)),
                ("skill_score", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("education_score", models.FloatField(default=0.0)),
                ("completeness", models.FloatField(default=0.0)),
                ("computed_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_talent_scores",
            },
        ),
        migrations.CreateModel(
            name="CentralUser",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(null=True)),
                ("last_login", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_users",
            },
        ),
        migrations.CreateModel(
            name="DeadLetterEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_event", models.UUIDField(db_index=True)),
                ("app_label", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=128)),
                ("instance_id", models.CharField(max_length=255)),
                ("operation", models.CharField(max_length=16)),
                ("payload", models.JSONField(default=dict)),
                ("last_error", models.TextField()),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "orch_dead_letter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FullSyncReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("total_synced", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "orch_full_sync_reports",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CentralAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField(db_index=True, null=True)),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                ("event_data", models.JSONField(default=dict)),
                ("session_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(db_index=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_analytics_events",
                "indexes": [
                    models.Index(
                        fields=["event_name", "created_at"],
                        name="central_ana_event_n_870a02_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CentralConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("consent_type", models.CharField(db_index=True, max_length=64)),
                ("is_granted", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("granted_at", models.DateTimeField(null=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_consent_records",
                "indexes": [
                    models.Index(
                        fields=["user_id", "consent_type"],
                        name="central_con_user_id_322926_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CentralMatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("profile_id", models.UUIDField(db_index=True)),
                ("opportunity_id", models.UUIDField(db_index=True)),
                ("score", models.FloatField(default=0.0)),
                ("match_factors", models.JSONField(default=dict)),
                ("is_recommended", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_match_scores",
                "indexes": [
                    models.Index(
                        fields=["profile_id", "opportunity_id"],
                        name="central_mat_profile_7301cf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CentralSecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("user_id", models.UUIDField(db_index=True, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(blank=True, max_length=16)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("details", models.JSONField(default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(db_index=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "central_security_events",
                "indexes": [
                    models.Index(
                        fields=["event_type", "severity", "created_at"],
                        name="central_sec_event_t_136ed3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_label", models.CharField(db_index=True, max_length=64)),
                ("model_name", models.CharField(db_index=True, max_length=128)),
                ("instance_id", models.CharField(db_index=True, max_length=255)),
                ("operation", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("dead", "Dead (exhausted retries)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "orch_sync_event_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["app_label", "model_name", "status"],
                        name="orch_sync_e_app_lab_ea9267_idx",
                    ),
                    models.Index(
                        fields=["status", "retry_count"],
                        name="orch_sync_e_status_f1d301_idx",
                    ),
                ],
            },
        ),
    ]
