# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this key", max_length=100
                    ),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=10)),
                ("key_hash", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("reason", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_blocked_ips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_service", "Terms of Service"),
                            ("cookie_policy", "Cookie Policy"),
                            ("marketing_email", "Marketing Emails"),
                            ("data_processing", "Data Processing"),
                            ("data_sharing", "Data Sharing with Partners"),
                            ("profiling", "AI Profiling & Matching"),
                            ("analytics", "Analytics & Usage Tracking"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("granted", "Consent Granted"),
                            ("withdrawn", "Consent Withdrawn"),
                            ("updated", "Consent Updated"),
                        ],
                        max_length=15,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("raw_request", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_consent_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "created_at"],
                        name="security_co_user_id_0d0e09_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("brute_force", "Brute-Force Login Attempt"),
                            ("account_locked", "Account Locked"),
                            ("suspicious_ip", "Suspicious IP Activity"),
                            ("token_abuse", "Token / API Key Abuse"),
                            ("csrf", "CSRF Violation"),
                            ("xss", "XSS Attempt"),
                            ("sqli", "SQL Injection Attempt"),
                            ("rate_limit", "Rate Limit Exceeded"),
                            ("data_export", "Bulk Data Export"),
                            ("priv_esc", "Privilege Escalation Attempt"),
                            ("unusual_access", "Unusual Access Pattern"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=512)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "severity", "created_at"],
                        name="security_ev_event_t_b10153_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="security_ev_ip_addr_b3ff8b_idx",
                    ),
                ],
            },
        ),
    ]
