# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opportunity_id", models.UUIDField(db_index=True)),
                ("opportunity_type", models.CharField(default="job", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("computed", "Computed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("skill_match", models.FloatField(default=0.0)),
                ("experience_match", models.FloatField(default=0.0)),
                ("education_match", models.FloatField(default=0.0)),
                ("location_match", models.FloatField(default=0.0)),
                ("salary_match", models.FloatField(default=0.0)),
                ("culture_match", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(db_index=True, default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("algorithm_version", models.CharField(default="v1", max_length=20)),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matching_scores",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("opportunity", "Opportunity"),
                            ("talent", "Talent Profile"),
                            ("skill", "Skill to Learn"),
                            ("connection", "Suggested Connection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField(db_index=True)),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                ("relevance_score", models.FloatField(db_index=True, default=0.0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "match_score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="matching.matchscore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matching_recommendations",
                "ordering": ["rank", "-relevance_score"],
            },
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.TextField(blank=True)),
                ("bio_text", models.TextField(blank=True)),
                ("skills_text", models.TextField(blank=True)),
                ("experience_text", models.TextField(blank=True)),
                ("education_text", models.TextField(blank=True)),
                ("skills_json", models.JSONField(blank=True, default=list)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, db_index=True, max_length=50)),
                ("availability", models.CharField(blank=True, max_length=30)),
                ("employment_types", models.JSONField(blank=True, default=list)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="ZAR", max_length=3)),
                ("overall_score", models.FloatField(db_index=True, default=0.0)),
                ("is_searchable", models.BooleanField(db_index=True, default=True)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matching_search_index",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["user", "overall_score"], name="matching_sc_user_id_f678a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["opportunity_id", "overall_score"],
                name="matching_sc_opportu_011491_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchscore",
            unique_together={("user", "opportunity_id")},
        ),
    ]
