# -*- coding: utf-8 -*-
"""
Blog article data for the ForgeForth Africa website.
This will eventually be replaced by a database-backed Blog model.
"""

ARTICLES = {
    "pretty-cv-ugly-truth": {
        "slug": "pretty-cv-ugly-truth",
        "title": "The Pretty CV, Ugly Truth: When Your Font Choice Matters More Than Your Skills",
        "excerpt": "A hilarious (and slightly painful) look at how the hiring world lost its mind — where Comic Sans is a crime but lacking actual skills is just fine.",
        "category": "Insights",
        "category_color": "pink",
        "author": "ForgeForth Team",
        "author_initials": "FF",
        "date": "Mar 3, 2026",
        "read_time": "6 min read",
        "featured": True,
        "tags": ["cv", "humor", "hiring", "skills", "employment"],
        "body": [
            ("Let me tell you a story. It's a tragedy, really. A comedy. A tragicomedy that plays out in HR offices across Africa every single day.", None),
            ("Picture this: Two candidates apply for the same job.", None),
            ("Candidate A has 10 years of experience, has built three successful businesses, speaks four languages, and once fixed a broken server at 3 AM using only a paperclip and sheer willpower. But their CV? It was made in Microsoft Word 2007. The margins are slightly off. They used Times New Roman. Like an animal.", None),
            ("Candidate B has six months of experience, most of which was spent figuring out how to use the coffee machine. But oh — their CV! It's a masterpiece. Designed in Canva with a beautiful teal accent color. Perfect spacing. A subtle drop shadow on the headings. Their profile photo has a ring light glow. Chef's kiss.", None),
            ("Guess who got the interview?", None),
            ("If you said Candidate B, congratulations. You understand modern hiring.", None),
            ("Welcome to the Circus", "h2"),
            ("Somewhere along the way, the hiring process lost its mind. We started caring more about presentation than substance. More about packaging than product.", None),
            ("Think about it. We live in a world where:", None),
            ("• Using the wrong font can get your CV thrown in the trash", None),
            ("• A two-page CV is 'too long' (apparently your entire life should fit on one page, ideally with 'white space')", None),
            ("• Having a photo is bad in some countries, required in others, and confusing everywhere", None),
            ("• 'Action verbs' matter more than actual actions", None),
            ("• The phrase 'detail-oriented' appears on 47 million CVs but nobody knows what it means", None),
            ("Meanwhile, whether you can actually DO the job? That's like... question number 17.", None),
            ("The Great Font Debate", "h2"),
            ("Let's talk about fonts for a second. Because apparently, this is what determines your career now.", None),
            ("Use Comic Sans? You're clearly a psychopath who shouldn't be trusted with responsibilities.", None),
            ("Use Times New Roman? What is this, 1998? Did you also arrive to work on a horse?", None),
            ("Use Calibri? Ah, the default font. The 'I didn't even try' of font choices.", None),
            ("Use something fancy like Garamond? Now we're talking. You clearly have taste. You're hired. We don't even need to know if you can do the job.", None),
            ("I'm being dramatic, but only slightly. There are actual studies showing that CVs with certain fonts get more callbacks. Not because the candidates are better. Because the FONT is more pleasing to the human eye.", None),
            ("Your entire career. Decided by typography.", None),
            ("The Skills Nobody Asked About", "h2"),
            ("Here's what kills me. While HR is debating whether your CV has the right 'visual hierarchy,' nobody is asking the important questions:", None),
            ("Can you solve problems when things go wrong?", None),
            ("Can you work with difficult people without losing your mind?", None),
            ("Can you learn new things quickly?", None),
            ("Can you actually do the work?", None),
            ("Nope. Instead, let's spend 30 seconds scanning for keywords and checking if the bullet points are aligned.", None),
            ("I once heard of a company that rejected a brilliant candidate because there was a typo on page two of their CV. One typo. The candidate had 15 years of experience and came highly recommended. But that missing letter? Unforgivable. How could they possibly trust someone who once, in a moment of human error, typed 'managment' instead of 'management'?", None),
            ("Meanwhile, they hired someone whose CV was flawless but who turned out to spend most of their time watching YouTube videos and taking 2-hour lunch breaks.", None),
            ("The Real Joke Is On All Of Us", "h2"),
            ("The funniest part? Everyone knows this system is broken. HR knows it. Managers know it. Candidates definitely know it.", None),
            ("But we keep playing the game.", None),
            ("Candidates spend hours — sometimes days — perfecting their CVs. Choosing the right template. Agonizing over whether to use 'Managed a team' or 'Led a team' or 'Spearheaded a team' (spearheaded sounds more aggressive, right? More leadership-y?).", None),
            ("They hire CV writers. They buy premium templates. They watch YouTube tutorials on 'How to Make Your CV Stand Out.' They treat their CV like it's a work of art going into a museum.", None),
            ("And companies? They buy fancy software that scans CVs for keywords. If your CV doesn't have the magic words, you're automatically rejected. A robot decides your fate based on whether you wrote 'utilized' instead of 'used.'", None),
            ("The whole thing is absurd. And kind of sad.", None),
            ("What We Should Actually Care About", "h2"),
            ("Imagine a different world. A world where:", None),
            ("• You could show what you've actually built instead of just describing it", None),
            ("• Your skills could be verified and demonstrated, not just listed", None),
            ("• Employers could see your work, your projects, your problem-solving abilities", None),
            ("• A farmer could be evaluated on their yields, not their CV design", None),
            ("• A mechanic could be judged on vehicles they've fixed, not fonts they've chosen", None),
            ("• A developer could share their code, not just bullet points about their code", None),
            ("Sounds crazy, right? Actually showing what you can do instead of writing about it prettily?", None),
            ("That's the world ForgeForth Africa is building.", None),
            ("The Punchline", "h2"),
            ("Here's the thing. We're not saying CVs are useless. They have their place. But they should be the starting point, not the entire evaluation.", None),
            ("A CV tells you what someone claims they can do. It doesn't tell you if they can actually do it.", None),
            ("It's like judging a chef by their menu design instead of tasting their food. Or hiring a driver based on how nicely they describe driving instead of watching them drive.", None),
            ("We've built a system where the wrapper matters more than what's inside. And then we wonder why so many hires don't work out.", None),
            ("Maybe — just maybe — we should try something different.", None),
            ("At ForgeForth Africa, we believe your skills should speak louder than your font choice. We believe a welder should be judged by their welds, a teacher by their teaching, a builder by what they've built.", None),
            ("Because at the end of the day, nobody ever looked at a finished building and said, 'Wow, I wonder what font the construction workers used on their CVs.'", None),
            ("Join us. Bring your skills. Leave the drop shadows at home.", None),
        ],
    },
    "the-suit-and-tie-myth": {
        "slug": "the-suit-and-tie-myth",
        "title": "The Suit & Tie Myth: Why Your Skills Matter More Than What You Wear",
        "excerpt": "For generations, Africans have been taught that success means an office job in formal clothes. It's time to break free from this limiting belief and embrace the power of real skills.",
        "category": "Insights",
        "category_color": "orange",
        "author": "ForgeForth Team",
        "author_initials": "FF",
        "date": "Mar 3, 2026",
        "read_time": "8 min read",
        "featured": True,
        "tags": ["skills", "mindset", "africa", "employment"],
        "body": [
            ("Growing up in Africa, many of us heard the same message over and over: 'Study hard, get a degree, find a good office job.' The image of success was always the same - a man or woman in a suit and tie, sitting behind a desk in an air-conditioned office, looking important.", None),
            ("But here's the truth nobody told us: that image is a lie. A dangerous one.", None),
            ("Where Did This Belief Come From?", "h2"),
            ("The 'suit and tie' mentality didn't come from nowhere. It was inherited from colonial times, when administrative jobs were seen as the pinnacle of achievement. Working with your hands was considered 'low class.' Office work was 'respectable.'", None),
            ("This mindset was passed down through generations. Our parents told us. Our schools reinforced it. Society celebrated the lawyer, the banker, the government official. The farmer? The mechanic? The artisan? They were seen as people who 'didn't make it.'", None),
            ("The Damage This Has Done", "h2"),
            ("This belief has done enormous harm to Africa's economy and to millions of individuals.", None),
            ("First, it created massive unemployment. Everyone chased the same limited number of 'respectable' jobs while practical, hands-on work was ignored. Today, we have millions of graduates with degrees sitting at home unemployed, while there's a desperate shortage of skilled plumbers, electricians, welders, and technicians.", None),
            ("Second, it made people ashamed of their real talents. How many young Africans are brilliant cooks, talented tailors, or skilled builders - but feel embarrassed to pursue these paths because their families want them to be 'professionals'?", None),
            ("Third, it disconnected us from reality. Africa's economies need farmers to grow food, mechanics to fix vehicles, carpenters to build homes, and manufacturers to produce goods. These are not backup plans. These are essential skills that power our continent.", None),
            ("The World Is Changing - And So Should We", "h2"),
            ("Here's what's interesting: the rest of the world is starting to realize what Africa forgot - that skills matter more than titles.", None),
            ("In Europe, a skilled plumber earns more than many office workers. In Germany, vocational training is respected just as much as university education. In the US, companies like Google and Apple have stopped requiring degrees altogether - they just want people who can do the job.", None),
            ("The global economy is shifting towards skills-first thinking. And Africa has the opportunity to lead this change, if we can let go of outdated beliefs.", None),
            ("What Does Real Success Look Like?", "h2"),
            ("Let's be honest about what success really means.", None),
            ("Is a tailor who employs 10 people, feeds their family, and creates beautiful clothes less successful than an office worker who sits in traffic for 3 hours a day and barely makes rent? Is a farmer who feeds thousands of people less valuable than someone pushing papers in an office?", None),
            ("Success is not about what you wear. It's about what you can do, what problems you can solve, and how you contribute to your community and economy.", None),
            ("A welder who can fix industrial equipment is a hero. A mechanic who keeps vehicles running is essential. A hairdresser who makes people feel confident is changing lives. A carpenter who builds homes is literally creating shelter.", None),
            ("These skills are not 'less than.' They are the backbone of every economy in the world.", None),
            ("The Skills Africa Actually Needs", "h2"),
            ("Look around you. What does your community actually need?", None),
            ("It needs people who can grow food and get it to markets. It needs people who can build and repair homes. It needs people who can fix machines, vehicles, and electronics. It needs people who can create products that can be sold locally and exported. It needs healthcare workers who can take care of the sick. It needs teachers who can educate the next generation.", None),
            ("Notice what's not on that list? It's not 'more people in suits sitting in offices.' The skills Africa needs are practical, hands-on, and real.", None),
            ("Breaking Free From The Myth", "h2"),
            ("If you're a young African trying to figure out your path, here's what we want you to know:", None),
            ("Your skills are valuable - whatever they are. If you're good with your hands, that's a gift. If you can fix things, grow things, build things, create things - that's not a backup plan. That's a superpower.", None),
            ("Don't let anyone make you feel small because your talent doesn't come with an office and a tie. The world needs what you can do.", None),
            ("How ForgeForth Africa Is Changing This", "h2"),
            ("At ForgeForth Africa, we don't care what you wear. We care what you can do.", None),
            ("Our platform is built to recognize ALL skills - not just the ones that look good on a traditional CV. Whether you're a software developer, a skilled farmer, a talented chef, a master welder, or anything in between - if you have skills, you belong here.", None),
            ("We're connecting skilled Africans with opportunities that value what they can actually do. We're building a future where your abilities matter more than your appearance, where your work speaks louder than your wardrobe.", None),
            ("A Message to Parents and Educators", "h2"),
            ("If you're a parent or teacher reading this, we have a request: please stop telling young people that only office jobs are 'real jobs.'", None),
            ("Encourage the child who loves cooking to master that craft. Support the teenager who's fascinated by machines. Celebrate the young person who wants to farm. These paths can lead to fulfilling, successful, prosperous lives.", None),
            ("The suit and tie was never the goal. A meaningful life where you use your talents and contribute to your community - that's the real goal.", None),
            ("The Future Belongs to the Skilled", "h2"),
            ("Africa's future will not be built by people sitting in offices looking important. It will be built by people who can do things - who can create, fix, build, grow, and make.", None),
            ("The countries that thrive in the coming decades will be the ones that recognize and develop all types of talent, not just the 'professional' ones. Africa has an abundance of skilled, hardworking people. It's time we started celebrating them.", None),
            ("So here's our challenge to you: What can you actually do? What skills do you have that the world needs? Don't be ashamed of them. Develop them. Master them. Let them shine.", None),
            ("Because there's power beyond a poor resume - and there's success beyond a suit and tie.", None),
        ],
    },
    "africa-talent-revolution": {
        "slug": "africa-talent-revolution",
        "title": "Africa's Talent Revolution: Why the World Is Finally Paying Attention",
        "excerpt": "For decades, Africa's greatest resource has been overlooked. Not oil. Not diamonds. Not gold. Its people. We explore why 2025 marks the turning point.",
        "category": "Insights",
        "category_color": "amber",
        "author": "ForgeForth Team",
        "author_initials": "FF",
        "date": "Feb 18, 2026",
        "read_time": "6 min read",
        "featured": True,
        "tags": ["talent", "africa", "future of work"],
        "body": [
            ("For too long, the narrative around Africa has been shaped by what it lacks. Infrastructure gaps. Funding shortfalls. Brain drain. But 2025 changed something. Global companies - from Silicon Valley giants to European multinationals - began turning their attention south and asking: where is the next wave of talent coming from?", None),
            ("The answer, increasingly, is Africa.", None),
            ("Africa is Rich - But Not How You Think", "h2"),
            ("When most people think of Africa's wealth, they think of natural resources. And yes - the continent holds 30% of the world's mineral reserves, 60% of its arable land, and some of the largest oil and gas deposits on Earth. But there is another resource that dwarfs all of these combined: people.", None),
            ("Africa's population stands at 1.4 billion. The median age is 19.7 years. By 2030, Africa will have the world's largest workforce - over 420 million people of working age. And critically, this population is educated, connected, and hungry.", None),
            ("The Numbers Tell a Story", "h2"),
            ("African tech funding reached $6.5 billion in 2022, up from just $2 billion in 2019. There are now over 700 tech hubs across the continent. Nigeria alone produces more software developers than most European nations. Kenya's Nairobi has been dubbed the 'Silicon Savannah'. South Africa's Cape Town is home to a booming startup ecosystem.", None),
            ("This is not anecdotal. These are structural shifts - driven by mobile connectivity, affordable smartphones, and a generation that grew up building.", None),
            ("What ForgeForth Africa Is Doing About It", "h2"),
            ("We believe the problem has never been a lack of talent. It has been a lack of infrastructure to connect that talent to opportunity. ForgeForth Africa is building the alternative. An AI-powered, skills-first platform that sees the whole person - not just their CV.", None),
            ("The revolution is not coming. It is already here. We are just making sure Africa gets to lead it.", None),
        ],
    },
    "beyond-the-resume": {
        "slug": "beyond-the-resume",
        "title": "There's Power Beyond a Poor Resume: Skills-First Hiring Is Here",
        "excerpt": "Traditional resumes were never designed to capture what truly makes someone great at their work. We're building the alternative.",
        "category": "Platform",
        "category_color": "blue",
        "author": "Product Team",
        "author_initials": "PT",
        "date": "Feb 12, 2026",
        "read_time": "5 min read",
        "featured": False,
        "tags": ["skills", "hiring", "platform"],
        "body": [
            ("A resume is, at best, a rough approximation of a person. At worst, it is a gatekeeping mechanism that filters out extraordinary talent because they went to the wrong school, worked for an unknown company, or simply did not know how to market themselves on a single page.", None),
            ("We built ForgeForth Africa because we believe there is power beyond a poor resume.", None),
            ("The Problem With Resumes", "h2"),
            ("Resumes were invented in the 1950s. The world of work has changed beyond recognition since then - but hiring has not kept up.", None),
            ("Skills Are the New Currency", "h2"),
            ("The shift to skills-based hiring is not a trend - it is an inevitability. Companies like IBM, Google, and Apple have already dropped degree requirements for many roles.", None),
            ("What This Means for Africa", "h2"),
            ("For African talent specifically, this shift is transformational. Many of Africa's most brilliant minds built their skills outside formal institutions - through self-teaching, community projects, freelance work, and sheer necessity.", None),
            ("There is power beyond a poor resume. ForgeForth Africa exists to unlock it.", None),
        ],
    },
    "54-nations-one-vision": {
        "slug": "54-nations-one-vision",
        "title": "54 Nations, One Vision: Building a Pan-African Talent Network",
        "excerpt": "From Cairo to Cape Town, Dakar to Dar es Salaam - ForgeForth is connecting talent across every corner of the continent.",
        "category": "Mission",
        "category_color": "green",
        "author": "ForgeForth Team",
        "author_initials": "FF",
        "date": "Feb 5, 2026",
        "read_time": "7 min read",
        "featured": False,
        "tags": ["pan-africa", "network", "mission"],
        "body": [
            ("Africa is not a country. It is 54 countries, over 2,000 languages, 3,000 ethnic groups, and a diversity of cultures, climates, and economies that defies easy generalisation.", None),
            ("Why Pan-African Matters", "h2"),
            ("The African Continental Free Trade Area (AfCFTA) - the world's largest free trade zone by number of countries - is proof that Africa is integrating.", None),
            ("ForgeForth Africa is built from the ground up for the continent. Multi-language support. Regional compliance. Cross-border payment systems. We are not adapting a Western product for Africa - we are building an African product for the world.", None),
            ("From Cairo to Pretoria", "h2"),
            ("Our vision is a talent infrastructure that spans the entire continent. From Cairo, Egypt in the north to Pretoria, South Africa in the south.", None),
        ],
    },
    "ai-matching-explained": {
        "slug": "ai-matching-explained",
        "title": "How Our AI Matching Engine Actually Works",
        "excerpt": "Under the hood of ForgeForth's intelligent skills-based matching system - built to eliminate bias and surface the best talent, fast.",
        "category": "Technology",
        "category_color": "purple",
        "author": "Engineering Team",
        "author_initials": "ET",
        "date": "Jan 28, 2026",
        "read_time": "8 min read",
        "featured": False,
        "tags": ["AI", "technology", "matching"],
        "body": [
            ("One of the questions we get most often is: how does the matching actually work? 'AI-powered' has become a marketing term so overused it has lost almost all meaning. So let us be specific.", None),
            ("Skills Extraction First", "h2"),
            ("Before we can match anyone to anything, we need to understand who they are. Our NLP pipeline processes uploaded CVs, portfolio links, video introductions, and completed skill assessments.", None),
            ("The Matching Algorithm", "h2"),
            ("Once we have skill vectors for both talent and opportunity, matching becomes a multi-dimensional similarity problem. We use cosine similarity for skill overlap, gradient-boosted models for success prediction, and reinforcement learning from historical match outcomes.", None),
            ("Eliminating Bias", "h2"),
            ("Bias in hiring is not just unethical - it is economically irrational. Our models are audited regularly for demographic bias.", None),
        ],
    },
    "volunteer-to-career": {
        "slug": "volunteer-to-career",
        "title": "From Volunteer to Career: Africa's Untapped Pathway to Opportunity",
        "excerpt": "Millions of Africans build world-class skills through volunteering and internships. ForgeForth is making sure that work counts.",
        "category": "Stories",
        "category_color": "orange",
        "author": "Community Team",
        "author_initials": "CT",
        "date": "Jan 20, 2026",
        "read_time": "4 min read",
        "featured": False,
        "tags": ["volunteer", "internship", "career"],
        "body": [
            ("Across Africa, there are millions of people doing remarkable work - teaching communities to code, building local health infrastructure, training young people in financial literacy - who receive no formal recognition.", None),
            ("Why Volunteer Experience Matters", "h2"),
            ("When someone spends two years running digital literacy workshops for 500 students, they are demonstrating curriculum design, public speaking, project management, and stakeholder communication.", None),
            ("How ForgeForth Captures It", "h2"),
            ("Our platform allows talent to log volunteer and internship experiences with the same rigour as formal employment.", None),
        ],
    },
    "employers-guide-africa": {
        "slug": "employers-guide-africa",
        "title": "The Employer's Guide to Hiring African Talent in 2026",
        "excerpt": "A practical, no-nonsense guide for global companies ready to tap into Africa's fastest-growing professional workforce.",
        "category": "For Employers",
        "category_color": "indigo",
        "author": "Partnerships Team",
        "author_initials": "PA",
        "date": "Jan 14, 2026",
        "read_time": "9 min read",
        "featured": False,
        "tags": ["employers", "hiring", "guide"],
        "body": [
            ("If you are a global employer and you are not actively considering African talent in your hiring strategy, you are leaving extraordinary value on the table.", None),
            ("Understand the Landscape", "h2"),
            ("Africa is not homogenous. Nigeria's tech ecosystem is different from South Africa's. Kenya's professional culture differs from Morocco's.", None),
            ("Skills-First, Always", "h2"),
            ("The single most important mindset shift for hiring African talent is moving to skills-first evaluation.", None),
            ("Compliance and Payments", "h2"),
            ("Cross-border employment in Africa does come with complexity. Our platform handles the compliance layer for you.", None),
            ("The Bottom Line", "h2"),
            ("The companies that build strong African talent pipelines today will have a significant competitive advantage within five years.", None),
        ],
    },
}

BLOG_CATEGORIES = ["All", "Insights", "Platform", "Mission", "Technology", "Stories", "For Employers"]

