# Generated by Django 5.2.7 on 2026-03-05 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV / Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("certificate", "Certificate"),
                            ("portfolio", "Portfolio Item"),
                            ("profile_photo", "Profile Photo"),
                            ("org_logo", "Organisation Logo"),
                            ("org_banner", "Organisation Banner"),
                            ("blog_image", "Blog Image"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Processing Failed"),
                            ("quarantine", "Quarantined (Security Risk)"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("stored_filename", models.CharField(max_length=255, unique=True)),
                ("file_path", models.CharField(max_length=512)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("extension", models.CharField(blank=True, max_length=20)),
                ("processed_path", models.CharField(blank=True, max_length=512)),
                ("thumbnail_path", models.CharField(blank=True, max_length=512)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("is_sanitised", models.BooleanField(default=False)),
                ("threat_detected", models.BooleanField(default=False)),
                ("threat_detail", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "media_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("extracted_text", models.TextField(blank=True)),
                ("pages", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="media.mediafile",
                    ),
                ),
            ],
            options={
                "db_table": "media_documents",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("sanitise", "Security Sanitisation"),
                            ("compress", "Image Compression"),
                            ("thumbnail", "Thumbnail Generation"),
                            ("ocr", "Text Extraction (OCR)"),
                            ("virus_scan", "Virus / Malware Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("celery_task", models.CharField(blank=True, max_length=255)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="media.mediafile",
                    ),
                ),
            ],
            options={
                "db_table": "media_processing_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["owner", "file_type"], name="media_files_owner_i_f7c04d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["status", "created_at"], name="media_files_status_d017bc_idx"
            ),
        ),
    ]
